/**
 * @fileoverview LithiaHost Orchestrator.
 * Responsible for the main-thread logic: building the project, loading manifests,
 * managing environment variables, and orchestrating worker thread lifecycles.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import { parseEnv } from "node:util";
import { isMainThread, Worker } from "node:worker_threads";
import {
	buildProject,
	type Event,
	type EventsManifest,
	type Route,
	type RoutesManifest,
	schemaVersion,
} from "@lithia-js/native";
import { green, logger } from "@lithia-js/utils";
import { type LithiaOptions, loadConfig } from "./config.mjs";
import { LithiaError } from "./errors/base.mjs";
import { ManifestVersionMismatchError } from "./errors/internal/index.mjs";
import { version } from "./meta.mjs";
import type { Environment } from "./types.js";
import { fileExists } from "./utils.mjs";

declare namespace globalThis {
	var isLithiaCLI: boolean | undefined;
	var __lithia_host_config_v1: LithiaOptions;
}

export const CFG_GLOBAL_KEY = "__lithia_host_config_v1" as const;

export interface LithiaOpts {
	environment: Environment;
}

/**
 * Standard communication protocol from Worker back to Host.
 */
export type WorkerToHostEvent =
	| { type: "ready" }
	| {
			type: "error";
			error: {
				name: string;
				message: string;
				stack?: string;
			};
	  };

/**
 * The Host is the manager of the Lithia process.
 * It stays alive even when the application code (running in the worker) crashes or reloads.
 */
export class LithiaHost {
	private _worker: Worker | null = null;
	private _config!: LithiaOptions;
	private _env: Record<string, string> = {};

	private _isWorkerRunning = false;
	private _isAppReady = false;
	private _workerCount = 0;
	private _lastPortUsed: number = 0;

	private _routes: Route[] = [];
	private _events: Event[] = [];

	constructor(private readonly opts: LithiaOpts) {
		if (!isMainThread) {
			throw new Error("LithiaHost must be instantiated in the Main Thread.");
		}
	}

	// --- Getters ---

	public get config(): LithiaOptions {
		return this.environment === "production"
			? globalThis[CFG_GLOBAL_KEY]
			: this._config;
	}

	public get environment(): Environment {
		return this.opts.environment;
	}
	public get isAppReady(): boolean {
		return this._isAppReady;
	}
	public get routes(): Route[] {
		return this._routes;
	}
	public get events(): Event[] {
		return this._events;
	}

	// --- Configuration & Env Loading ---

	/**
	 * Loads the Lithia configuration file.
	 */
	public async loadConfig(): Promise<void> {
		if (this.environment === "production") return;
		this._config = await loadConfig();
		this._lastPortUsed = this._config.http.port;
	}

	/**
	 * Resolves and parses defined .env files.
	 */
	public async loadEnv(): Promise<void> {
		this.ensureConfigLoaded();
		const cwd = process.cwd();
		const envFiles = await this.getAvailableEnvFiles();

		for (const file of envFiles) {
			try {
				const raw = await readFile(path.join(cwd, file), "utf-8");
				const parsed = parseEnv(raw);
				Object.assign(this._env, parsed);
			} catch {
				logger.warn(`Failed to parse env file: ${file}`);
			}
		}
	}

	// --- Manifest Management ---

	/**
	 * Loads the routes manifest generated by the compiler.
	 */
	public async loadRoutes(): Promise<void> {
		const routes = await this.loadManifest<RoutesManifest>("routes.json");
		if (routes) this._routes = routes.routes;
	}

	/**
	 * Loads the events manifest generated by the compiler.
	 */
	public async loadEvents(): Promise<void> {
		const events = await this.loadManifest<EventsManifest>("events.json");
		if (events) this._events = events.events;
	}

	private async loadManifest<T extends { version: string }>(
		fileName: string,
	): Promise<T | null> {
		this.ensureConfigLoaded();
		const manifestPath = path.join(process.cwd(), this.config.outDir, fileName);

		if (!(await fileExists(manifestPath))) return null;

		const raw = await readFile(manifestPath, "utf-8");
		const manifest = JSON.parse(raw) as T;
		const currentSchema = schemaVersion();

		if (manifest.version !== currentSchema) {
			throw new ManifestVersionMismatchError(currentSchema, manifest.version);
		}

		return manifest;
	}

	// --- Build & Lifecycle ---

	/**
	 * Compiles the source code into the output directory using @lithia-js/native.
	 * @param throwOnError When true (default) rethrows the error to the caller
	 *                     (useful for CLI `build`). When false, errors are
	 *                     logged but the host keeps running (useful for dev).
	 */
	public build(): void {
		this.ensureConfigLoaded();
		const start = process.hrtime.bigint();

		try {
			const cwd = process.cwd();
			buildProject(
				path.join(cwd, this.config.sourceDir),
				path.join(cwd, this.config.outDir),
			);

			const duration = Number(process.hrtime.bigint() - start) / 1e6;
			logger.success(`Compiled successfully in ${duration.toFixed(2)}ms`);
		} catch (err) {
			logger.error(`Build failed with error: ${(err as Error).message}`);
			if (this.environment === "build") throw err;
		}
	}

	public async setup(): Promise<void> {
		await this.loadConfig();
		await this.loadEnv();
		await this.printHeader();
	}

	public async start(): Promise<void> {
		if (!this._config) await this.loadConfig();
		if (this._routes.length === 0) await this.loadRoutes();
		if (this._events.length === 0) await this.loadEvents();

		this.createWorker();
		logger.debug(`Instance started in ${this.environment} mode.`);
	}

	/**
	 * Restarts the worker thread (Hot Reload).
	 */
	public async reload(): Promise<void> {
		await this.loadRoutes();
		await this.loadEvents();
		await this.swapWorker();
	}

	public async stop(): Promise<void> {
		await this.disposeWorker();
		logger.debug("Lithia instance stopped.");
	}

	// --- Worker Operations ---

	private createWorker(): void {
		logger.debug("Spawning background worker...");

		this._worker = new Worker(path.join(import.meta.dirname, "_worker.mjs"), {
			workerData: {
				managedBy: "lithia",
				environment: this.environment,
				config: this.config,
				routes: this.routes,
				events: this.events,
				isFirstWorker:
					++this._workerCount === 1 ||
					this._lastPortUsed !== this.config.http.port,
			},
			env: { FORCE_COLOR: "1", ...this._env },
		});

		this._worker.on("message", (msg: WorkerToHostEvent) => {
			if (msg.type === "ready") {
				this._isAppReady = true;
				this._isWorkerRunning = true;
			}
		});

		this._worker.on("error", (err) => {
			logger.error("Worker Thread crashed:", err);
			this._isWorkerRunning = false;
		});
	}

	private async disposeWorker(): Promise<void> {
		if (!this._worker) return;
		await this._worker.terminate();
		this._worker = null;
		this._isWorkerRunning = false;
		this._isAppReady = false;
	}

	public async swapWorker(): Promise<void> {
		if (this._worker && this._isWorkerRunning) {
			await this.disposeWorker();
		}
		this.createWorker();
	}

	// --- UI Helpers ---

	public async printHeader(): Promise<void> {
		const files = await this.getAvailableEnvFiles();
		logger.event(green(`Lithia.js ${version}`));
		if (files.length) logger.info(`Environment: ${files.join(", ")}`);
		console.log();
	}

	public printRouteTree(): void {
		this.printTree(
			"Route",
			this.routes,
			(r) => `${(r.method || "all").toUpperCase()} ${r.path}`,
			(r) => (r.dynamic ? "ƒ" : "○"),
		);
	}

	public printEventTree(): void {
		this.printTree(
			"Event",
			this.events,
			(e) => e.name,
			() => "λ",
		);
	}

	private printTree<T>(
		label: string,
		items: T[],
		nameFn: (i: T) => string,
		symbolFn: (i: T) => string,
	): void {
		if (items.length === 0) return;
		console.log(`\n\x1b[4m${label} Tree:\x1b[0m`);
		items.forEach((item, idx) => {
			const isLast = idx === items.length - 1;
			const branch = isLast ? "└" : "├";
			console.log(`${branch} ${symbolFn(item)} ${nameFn(item)}`);
		});
	}

	private async getAvailableEnvFiles(): Promise<string[]> {
		const existing: string[] = [];
		for (const f of this.config.envFiles) {
			if (await fileExists(path.join(process.cwd(), f))) existing.push(f);
		}
		return existing;
	}

	private ensureConfigLoaded(): void {
		if (!this.config) throw new LithiaError("Configuration not loaded.");
	}
}
