import fs from "node:fs/promises";
import path from "node:path";

/**
 * Representa um item a ser tipado no manifesto global.
 */
export interface TypeDefinition {
	/** Nome identificador (ex: "users:create" ou "cleanup") */
	identifier: string;
	/** Caminho absoluto para o arquivo de origem (.ts ou .js) */
	filePath: string;
	/** Nome do export a ser importado (opcional, padrão 'default') */
	exportName?: string;
}

/**
 * Estrutura para expansão de múltiplas interfaces do Core.
 */
export interface GeneratorRegistry {
	/** Mapeamento para a interface LithiaFunctions */
	functions?: TypeDefinition[];
	/** Mapeamento para a interface LithiaEvents (exemplo de expansão futura) */
	events?: TypeDefinition[];
	/** Mapeamento para configurações de plugins ou middlewares */
	plugins?: TypeDefinition[];
}

/**
 * Gera um arquivo de definição de tipos (.d.ts) para prover IntelliSense
 * e Type Safety global nas APIs do Lithia.
 * * @param outRoot - O diretório de saída (geralmente o .lithia ou dist)
 * @param registry - Objeto contendo as definições de cada categoria
 */
export async function generateLithiaTypes(
	projectRoot: string,
	registry: GeneratorRegistry,
) {
	const dotLithiaDir = path.join(projectRoot, ".lithia");
	const imports: string[] = [];
	const moduleAugmentations: string[] = [];

	for (const [category, definitions] of Object.entries(registry)) {
		if (!definitions || definitions.length === 0) continue;

		const interfaceName = `Lithia${category.charAt(0).toUpperCase() + category.slice(1)}`;
		const interfaceLines: string[] = [];

		for (const def of definitions) {
			const typeAlias = `${category}_${toPascalCase(def.identifier)}`;
			// O caminho relativo agora é calculado a partir de .lithia/
			const importPath = relativeImportPath(dotLithiaDir, def.filePath);
			const member = def.exportName || "default";

			imports.push(
				`import { ${member} as ${typeAlias} } from "${importPath}";`,
			);
			interfaceLines.push(`    "${def.identifier}": typeof ${typeAlias};`);
		}

		moduleAugmentations.push(
			`  interface ${interfaceName} {\n${interfaceLines.join("\n")}\n  }`,
		);
	}

	const content = [
		"/* eslint-disable */",
		"/* This file is auto-generated by Lithia. Do not edit manually. */",
		imports.join("\n"),
		'\ndeclare module "@lithia-js/core" {',
		moduleAugmentations.join("\n\n"),
		"}",
	].join("\n");

	const lithiaTypesPath = path.join(dotLithiaDir, "lithia.d.ts");
	await fs.mkdir(dotLithiaDir, { recursive: true });
	await fs.writeFile(lithiaTypesPath, content, "utf-8");
}

/**
 * Converte strings com hífens ou espaços para PascalCase.
 */
function toPascalCase(str: string) {
	return str
		.replace(/[^a-zA-Z0-9]/g, "-")
		.replace(/(^\w|-\w)/g, (m) => m.replace("-", "").toUpperCase());
}

/**
 * Calcula o caminho relativo e limpa extensões para compatibilidade com ESM/TS.
 */
function relativeImportPath(from: string, to: string) {
	let rel = path.relative(from, to).replace(/\\/g, "/");
	if (!rel.startsWith(".")) rel = `./${rel}`;
	// Remove extensões comuns para manter o import limpo
	return rel.replace(/\.(ts|mts|js|mjs)$/, "");
}
