import { readFile } from "node:fs/promises";
import path from "node:path";
import type { LithiaOptions } from "../../config";
import type { Event, EventsManifest } from "../../discovery/events";
import type { Route, RoutesManifest } from "../../discovery/routes";
import type { TaskCore, TasksManifest } from "../../discovery/tasks";
import { ManifestVersionMismatchError } from "../../errors/internal/index";
import { version as currentSchema } from "../../meta";
import { fileExists } from "../../shared/filesystem";

type VersionedManifest = { version: string };

/**
 * Loads and caches the runtime manifests generated by the Lithia build step.
 */
export class ManifestStore {
	private _routes: Route[] = [];
	private _events: Event[] = [];
	private _tasks: TaskCore[] = [];

	constructor(private readonly getConfig: () => LithiaOptions) {}

	public get routes(): Route[] {
		return this._routes;
	}

	public get events(): Event[] {
		return this._events;
	}

	public get tasks(): TaskCore[] {
		return this._tasks;
	}

	/**
	 * Loads the routes manifest into memory.
	 */
	public async loadRoutes(): Promise<void> {
		const manifest = await this.loadManifest<RoutesManifest>("routes.json");
		if (manifest) this._routes = manifest.routes;
	}

	/**
	 * Loads the events manifest into memory.
	 */
	public async loadEvents(): Promise<void> {
		const manifest = await this.loadManifest<EventsManifest>("events.json");
		if (manifest) this._events = manifest.events;
	}

	/**
	 * Loads the async tasks manifest into memory.
	 */
	public async loadTasks(): Promise<void> {
		const manifest = await this.loadManifest<TasksManifest>("tasks.json");
		if (manifest) this._tasks = manifest.tasks;
	}

	/**
	 * Loads all runtime manifests in parallel.
	 */
	public async loadAll(): Promise<void> {
		await Promise.all([this.loadRoutes(), this.loadEvents(), this.loadTasks()]);
	}

	/**
	 * Reads, parses, and validates a versioned manifest from the build output.
	 */
	private async loadManifest<T extends VersionedManifest>(
		fileName: string,
	): Promise<T | null> {
		const manifestPath = path.join(
			process.cwd(),
			this.getConfig().outDir,
			fileName,
		);

		if (!(await fileExists(manifestPath))) return null;

		const raw = await readFile(manifestPath, "utf-8").catch((error) => {
			throw new Error(
				`Failed to read manifest '${fileName}' from '${manifestPath}': ${(error as Error).message}`,
			);
		});
		let manifest: T;
		try {
			manifest = JSON.parse(raw) as T;
		} catch (error) {
			throw new Error(
				`Failed to parse manifest '${fileName}' from '${manifestPath}': ${(error as Error).message}`,
			);
		}

		if (manifest.version !== currentSchema) {
			throw new ManifestVersionMismatchError(currentSchema, manifest.version);
		}

		return manifest;
	}
}
