#! /usr/bin/env node
/**
 * -----------------------------------------------------------------------------
 * LITHIA FRAMEWORK - PRODUCTION ENTRY POINT
 * -----------------------------------------------------------------------------
 * * WARNING: THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 * * This file is automatically generated by the Lithia CLI during the build
 * process. Any manual modifications will be lost when the project is rebuilt.
 * * For configuration changes, please modify your 'lithia.config' file or
 * environment variables.
 * * @generated
 * -----------------------------------------------------------------------------
 */

import type { LithiaConfig } from "@lithia-js/core";
import { CFG_GLOBAL_KEY, HostSupervisor } from "@lithia-js/core/_";

declare global {
	var __lithia_host_config_v1: LithiaConfig;
}

/**
 * The __CONFIG__ constant is a placeholder injected during the build step.
 * It contains the resolved application configuration for production.
 */
declare const __CONFIG__: LithiaConfig;

/**
 * Bootstraps the production environment and manages the host lifecycle.
 */
async function bootstrap(): Promise<void> {
	// Initialize the global configuration context
	globalThis[CFG_GLOBAL_KEY] = __CONFIG__;

	const lithia = new HostSupervisor({ environment: "production" });

	await lithia.setup();

	try {
		await lithia.start();
	} catch {
		// Initialization failure handled by the host internally
	}

	/**
	 * Orchestrates a graceful shutdown by stopping the host
	 * and releasing process resources.
	 */
	const shutdown = async (): Promise<void> => {
		try {
			await lithia.stop();
		} catch {
			// Ensure the process exits even if the stop sequence encounters an error
		} finally {
			process.exit(0);
		}
	};

	// Register process signal listeners for clean termination
	process.once("SIGINT", shutdown);
	process.once("SIGTERM", shutdown);
}

// Execute the bootstrap sequence and handle unhandled rejections
await bootstrap().catch(() => process.exit(1));
