/* auto-generated by NAPI-RS */
/* eslint-disable */
/** * Main entry point for the native build process, exposed to Node.js.
 * @param source_root The directory containing .mts source files.
 * @param out_root The target directory for compiled .mjs files.
 */
export declare function buildProject(sourceRoot: string, outRoot: string): void

/** Represents an individual event discovered in the project. */
export interface Event {
  /** The logical name of the event (e.g., "user.signup"). */
  name: string
  /** The physical path to the compiled .mjs handler file. */
  filePath: string
  /** Optional grouping for logical event isolation. */
  namespace?: string
}

/** The final structure of the generated events.json file. */
export interface EventsManifest {
  /** Schema version for compatibility checks. */
  version: string
  /** Flat list of all registered events. */
  events: Array<Event>
}

/** Metadata about a discovered file. */
export interface FileInfo {
  /** Path relative to the scan root (e.g., "src/index.mts"). */
  path: string
  /** Absolute path on the local disk. */
  fullPath: string
}

/** Serializable route representation sent to the host (N-API). */
export interface Route {
  /** Uppercase HTTP method (GET, POST, etc.) or null for 'all'. */
  method?: string
  /** Normalized URL path (e.g., /users/:id). */
  path: string
  /** Indicates if the path contains variable segments. */
  dynamic: boolean
  /** Path to the compiled .mjs file on disk. */
  filePath: string
  /** Regex string used by the runtime for fast URL matching. */
  regex: string
}

/** The top-level manifest file structure. */
export interface RoutesManifest {
  version: string
  routes: Array<Route>
}

/**
 * Scan a directory tree for files matching the provided `path_components`.
 *
 * `path_components` is a vector of path segments used as roots for the
 * scanner (for example `["examples/1-basic-api"]`). `options` may include
 * include/ignore globs. Returns a list of `FileInfo` describing discovered
 * files or an error which is converted into a `napi::Error` for the host.
 */
export declare function scanDir(pathComponents: Array<string>, options?: ScanOptions | undefined | null): Array<FileInfo>

/** Configuration for the scanner's filtering logic. */
export interface ScanOptions {
  /** List of glob patterns to include. */
  include?: Array<string>
  /** List of glob patterns to exclude. */
  ignore?: Array<string>
}

/**
 * Return the native crate version embedded at compile time.
 *
 * This returns the value of `CARGO_PKG_VERSION` so the host can verify the
 * native binary version matches expectations.
 */
export declare function schemaVersion(): string
