/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Build the project located at `source_root` and emit outputs to `out_root`.
 *
 * This function is exported to the host via N-API and performs the full
 * native compilation pipeline:
 * 1. Reads build configuration from `source_root`.
 * 2. Scans for TypeScript files matching `.ts`.
 * 3. Compiles files (in parallel) using the embedded SWC-based compiler.
 * 4. Aggregates compilation results and fails the build if there are errors.
 * 5. If route files exist in the output, produces a `routes.json` manifest
 *    containing route metadata consumed by the runtime.
 *
 * Errors are returned as `napi::Error` to be propagated to the host.
 * High-level build entrypoint for the native TypeScript builder.
 *
 * `build_project` coordinates scanning the source tree, applying route
 * conventions, and producing a `RoutesManifest` that can be consumed by the
 * runtime. Currently this function is a thin wrapper and may be expanded to
 * run parallel compilation and emit artifacts to disk.
 */
export declare function buildProject(sourceRoot: string, outRoot: string): void

/** Serializable event representation sent to the host (N-API). */
export interface Event {
  /** Event name (e.g., "chat:message" or "connection") */
  name: string
  /** Absolute filesystem path to the compiled handler (JS) file. */
  filePath: string
  /** Optional namespace (e.g., "chat" for "chat:message"). */
  namespace?: string
}

/** Manifest containing all discovered events, serializable to the host. */
export interface EventsManifest {
  /** Manifest version string. */
  version: string
  /** List of events. */
  events: Array<Event>
}

/**
 * Information about a discovered file.
 * - `path` is the path relative to the scanned directory (using `/` as
 *   separator on all platforms).
 * - `full_path` is the absolute filesystem path to the file.
 */
export interface FileInfo {
  /** Relative path from the scanned directory */
  path: string
  /** Absolute path from the filesystem root */
  fullPath: string
}

/**
 * Serializable route representation sent to the host (N-API).
 * Fields are camel-cased to be idiomatic on the JavaScript side.
 */
export interface Route {
  /** Uppercase HTTP method name, e.g. `GET` or `POST`, when present. */
  method?: string
  /** Normalized route path (always starting with `/`). */
  path: string
  /** True when the route contains dynamic segments. */
  dynamic: boolean
  /** Absolute filesystem path to the source file backing the route. */
  filePath: string
  /** Generated route matching regex as a string. */
  regex: string
}

/** Manifest containing all discovered routes, serializable to the host. */
export interface RoutesManifest {
  /** Manifest version string. */
  version: string
  /** List of routes. */
  routes: Array<Route>
}

/**
 * Scan a directory tree for files matching the provided `path_components`.
 *
 * `path_components` is a vector of path segments used as roots for the
 * scanner (for example `["examples/1-basic-api"]`). `options` may include
 * include/ignore globs. Returns a list of `FileInfo` describing discovered
 * files or an error which is converted into a `napi::Error` for the host.
 */
export declare function scanDir(pathComponents: Array<string>, options?: ScanOptions | undefined | null): Array<FileInfo>

/**
 * Options controlling scanning behaviour.
 * - `include`: list of glob patterns that select files to include. If
 *   omitted or empty, the scanner returns an empty result set.
 * - `ignore`: optional list of glob patterns used to exclude matching files
 *   from the previously included set.
 */
export interface ScanOptions {
  /** Glob patterns to include files. */
  include?: Array<string>
  /** Glob patterns to ignore (applied after include matching). */
  ignore?: Array<string>
}

/**
 * Return the native crate version embedded at compile time.
 *
 * This returns the value of `CARGO_PKG_VERSION` so the host can verify the
 * native binary version matches expectations.
 */
export declare function schemaVersion(): string
