/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function buildProject(sourceRoot: string, outRoot: string): void

export interface Event {
  name: string
  filePath: string
  namespace?: string
}

export interface EventsManifest {
  version: string
  events: Array<Event>
}

export interface FileInfo {
  path: string
  fullPath: string
}

/**
 * Serializable route representation sent to the host (N-API).
 * Fields are camel-cased to be idiomatic on the JavaScript side.
 */
export interface Route {
  /** Uppercase HTTP method name, e.g. `GET` or `POST`, when present. */
  method?: string
  /** Normalized route path (always starting with `/`). */
  path: string
  /** True when the route contains dynamic segments. */
  dynamic: boolean
  /** Absolute filesystem path to the source file backing the route. */
  filePath: string
  /** Generated route matching regex as a string. */
  regex: string
}

/** Manifest containing all discovered routes, serializable to the host. */
export interface RoutesManifest {
  /** Manifest version string. */
  version: string
  /** List of routes. */
  routes: Array<Route>
}

/**
 * Scan a directory tree for files matching the provided `path_components`.
 *
 * `path_components` is a vector of path segments used as roots for the
 * scanner (for example `["examples/1-basic-api"]`). `options` may include
 * include/ignore globs. Returns a list of `FileInfo` describing discovered
 * files or an error which is converted into a `napi::Error` for the host.
 */
export declare function scanDir(pathComponents: Array<string>, options?: ScanOptions | undefined | null): Array<FileInfo>

export interface ScanOptions {
  include?: Array<string>
  ignore?: Array<string>
}

/**
 * Return the native crate version embedded at compile time.
 *
 * This returns the value of `CARGO_PKG_VERSION` so the host can verify the
 * native binary version matches expectations.
 */
export declare function schemaVersion(): string
